def X(name,systems,equipment,pattern,plane='multi',level=1,complexity=1,fatigue=2): return {'name':name,'systems':set(systems),'equipment':equipment,'pattern':pattern,'plane':plane,'level':level,'complexity':complexity,'fatigue':fatigue}
E=[]
def add(*a,**k): E.append(X(*a,**k))
# Resistance / strength
for a in [
('Goblet Squat',['strength','lower'],'Dumbbells','squat'),('Barbell Back Squat',['strength','lower'],'Barbell','squat', 'sagittal',2,2,4),('Front Squat',['strength','lower'],'Barbell','squat','sagittal',2,2,4),('Rear Foot Elevated Split Squat',['strength','lower','unilateral'],'Dumbbells','lunge'),('Reverse Lunge',['strength','lower','unilateral'],'Dumbbells','lunge'),('Single Leg RDL',['strength','lower','unilateral','contralateral','stability'],'Dumbbells','hinge','sagittal',2,2,3),('Romanian Deadlift',['strength','lower'],'Barbell','hinge','sagittal',2,2,4),('Trap Bar Deadlift',['strength','lower','power'],'Barbell','hinge','sagittal',3,3,5),('Hip Thrust',['strength','lower'],'Barbell','hip_extension','sagittal',2,2,3),('Bench Press',['strength','upper'],'Barbell','horizontal_push','transverse',2,2,4),('Dumbbell Bench Press',['strength','upper'],'Dumbbells','horizontal_push','transverse',1,1,3),('Overhead Press',['strength','upper'],'Barbell','vertical_push','sagittal',2,2,3),('Single Arm Dumbbell Press',['strength','upper','unilateral','contralateral'],'Dumbbells','vertical_push','multi',2,2,3),('Landmine Press',['strength','upper','power','unilateral','contralateral'],'Landmine','diagonal_push','multi',2,3,4),('Pull Up',['strength','upper'],'Pull-up Bar','vertical_pull','sagittal',2,2,3),('Lat Pulldown',['strength','upper'],'Cable/Machine','vertical_pull'),('Seated Cable Row',['strength','upper'],'Cable/Machine','horizontal_pull'),('Single Arm Dumbbell Row',['strength','upper','unilateral','contralateral'],'Dumbbells','horizontal_pull','transverse'),('Cable Face Pull',['strength','upper','stability'],'Cable/Machine','scapular_pull'),('Pallof Press',['stability','core','anti_rotation'],'Cable/Machine','anti_rotation','transverse'),('Side Plank',['stability','core','unilateral'],'Bodyweight','anti_lateral','frontal'),('Dead Bug',['corrective','core','stability'],'Bodyweight','anti_extension','sagittal'),('Glute Bridge',['corrective','activation'],'Bodyweight','hip_extension','sagittal'),('90/90 Hip Flow',['mobility','corrective'],'Bodyweight','hip_mobility'),('T-Spine Windmill',['mobility','corrective'],'Bodyweight','rotation'),('Ankle Rocker',['mobility','corrective'],'Bodyweight','ankle')]: add(*a)
# Power / agility / coordination
for a in [('Lateral Bound and Stick',['power','plyometric','agility','unilateral'],'Bodyweight','bound','frontal',2,2,3),('Skater Bound',['power','plyometric','agility','unilateral'],'Bodyweight','bound','frontal',2,2,3),('Box Jump',['power','plyometric'],'Box/Bench','jump','sagittal'),('Broad Jump',['power','plyometric'],'Bodyweight','jump'),('Split Squat Jump',['power','plyometric','unilateral'],'Bodyweight','jump','sagittal',2,2,3),('Depth Drop to Stick',['power','plyometric','stability'],'Box/Bench','landing','sagittal',3,3,5),('Pogo Jump',['power','plyometric'],'Bodyweight','jump'),('Reactive Cone Drill',['agility','speed','coordination'],'Cones','change_direction','frontal'),('Lateral Shuffle to Sprint',['agility','speed'],'Cones','sprint'),('Mirror Footwork',['agility','coordination'],'Cones','change_direction'),('Reaction Ball Catch',['coordination','neuromuscular'],'Bodyweight','reaction'),('Medicine Ball Rotational Scoop Toss',['power','sport','unilateral'],'Medicine Ball','rotation','transverse'),('Medicine Ball Chest Pass',['power','upper','sport'],'Medicine Ball','horizontal_push'),('Medicine Ball Overhead Throw',['power','sport'],'Medicine Ball','overhead'),('Shadow Boxing',['sport','speed','coordination','anaerobic'],'Bodyweight','rotation'),('Sprawl to Stand',['sport','power','coordination','anaerobic'],'Bodyweight','combined','sagittal',3,3,4),('Kumite Reaction Step',['sport','speed','agility','coordination'],'Bodyweight','change_direction'),('Shadow Kick Combination',['sport','power','coordination'],'Bodyweight','rotation','multi',2,2,3),('Soccer Ball Reactive Touch',['sport','coordination','agility'],'Bodyweight','reaction'),('Goalkeeper Lateral Dive Pattern',['sport','agility','power','coordination'],'Bodyweight','dive','frontal',3,3,4),('Winger Curved Sprint',['sport','speed','agility'],'Cones','sprint'),('Tennis Split Step + Crossover',['sport','agility','speed','unilateral'],'Bodyweight','change_direction'),('Swimming Band Pull Pattern',['sport','upper','activation'],'Bands','pull'),('Streamline Squat Jump',['sport','power','plyometric'],'Bodyweight','jump')]: add(*a)
# Advanced integrated compounds
for a in [('Single-Arm Row -> Single-Leg Deadlift',['strength','coordination','neuromuscular','unilateral','contralateral'],'Dumbbells','combined','multi',3,4,4),('Single-Arm Row -> Single-Leg RDL -> Opposite Press',['strength','power','coordination','neuromuscular','unilateral','contralateral'],'Dumbbells','combined','multi',4,5,5),('RFESS -> Contralateral Row',['strength','coordination','unilateral','contralateral'],'Dumbbells','combined','multi',3,4,4),('Single-Leg RDL -> Single-Arm Press',['strength','power','coordination','unilateral','contralateral'],'Dumbbells','combined','multi',3,4,4),('Single-Arm Row + Opposite Shoulder Press on Balance Pad',['strength','coordination','neuromuscular','unilateral','contralateral'],'Dumbbells','combined','multi',4,5,5),('Dumbbell Clean -> Push Press',['strength','power','coordination'],'Dumbbells','combined','multi',2,3,4)]: add(*a)
# MetCon stations
for a in [('Bike Sprint',['metcon','anaerobic'],'Bike/Row/SkiErg','conditioning'),('Row Intervals',['metcon','aerobic','anaerobic'],'Bike/Row/SkiErg','conditioning'),('SkiErg Intervals',['metcon','aerobic'],'Bike/Row/SkiErg','conditioning'),('Battle Rope Intervals',['metcon','anaerobic'],'Battle Rope','conditioning'),('Sled Push',['metcon','anaerobic','strength'],'Sled','push','sagittal',2,2,4),('Burpee',['metcon','anaerobic'],'Bodyweight','combined'),('Shuttle Sprint',['metcon','anaerobic','speed'],'Cones','sprint')]: add(*a)
EX={x['name']:x for x in E}
