# UTF-8 exercise database. Keep names plain ASCII to avoid mobile encoding corruption.
EX = [
# name, categories, equipment, pattern, plane, level, purpose
('Bench Press',['strength','upper','push','bilateral'],'Barbell','Horizontal Push','Sagittal','Intermediate','upper-body pressing strength'),
('Incline Dumbbell Press',['strength','upper','push','unilateral'],'Dumbbells','Horizontal Push','Sagittal','Intermediate','upper chest and shoulder strength'),
('Single Arm Dumbbell Row',['strength','upper','pull','unilateral','contralateral'],'Dumbbells','Horizontal Pull','Transverse','Intermediate','unilateral pulling and trunk control'),
('Seated Cable Row',['strength','upper','pull','bilateral'],'Cable/Machine','Horizontal Pull','Sagittal','Intermediate','upper-back strength'),
('Lat Pulldown',['strength','upper','pull','bilateral'],'Cable/Machine','Vertical Pull','Sagittal','Intermediate','lat and shoulder-girdle strength'),
('Overhead Press',['strength','upper','push','bilateral'],'Barbell','Vertical Push','Sagittal','Intermediate','shoulder pressing strength'),
('Single Arm Landmine Press',['strength','upper','push','unilateral','contralateral'],'Landmine','Vertical Push','Multi-planar','Advanced','athletic unilateral pressing'),
('Pull Up',['strength','upper','pull','bilateral'],'Pull-up Bar','Vertical Pull','Sagittal','Advanced','vertical pulling strength'),
('Dip',['strength','upper','push','bilateral'],'Dip Station','Horizontal Push','Sagittal','Intermediate','triceps and chest strength'),
('Barbell Back Squat',['strength','lower','squat','bilateral'],'Barbell','Squat','Sagittal','Advanced','whole lower-body strength'),
('Front Squat',['strength','lower','squat','bilateral'],'Barbell','Squat','Sagittal','Advanced','quad and trunk strength'),
('Romanian Deadlift',['strength','lower','hinge','bilateral'],'Barbell','Hinge','Sagittal','Intermediate','posterior-chain strength'),
('Barbell Hip Thrust',['strength','lower','hinge','bilateral'],'Barbell','Hip Extension','Sagittal','Intermediate','hip-extension strength'),
('Rear Foot Elevated Split Squat',['strength','lower','squat','unilateral','contralateral'],'Dumbbells','Split Squat','Sagittal','Intermediate','single-leg strength'),
('Lateral Lunge',['strength','lower','unilateral','ipsilateral'],'Dumbbells','Lunge','Frontal','Intermediate','frontal-plane strength'),
('Single Leg RDL',['strength','lower','hinge','unilateral','contralateral'],'Dumbbells','Hinge','Multi-planar','Intermediate','single-leg posterior-chain control'),
('Goblet Squat',['strength','lower','squat','bilateral'],'Dumbbells','Squat','Sagittal','Beginner','general lower-body strength'),
('Glute Bridge',['corrective','activation','lower','bilateral'],'Bodyweight','Hip Extension','Sagittal','Beginner','hip activation'),
('Dead Bug',['corrective','core','bilateral'],'Bodyweight','Anti-extension','Sagittal','Beginner','trunk control'),
('Side Plank',['stability','core','unilateral'],'Bodyweight','Anti-lateral flexion','Frontal','Beginner','lateral trunk stability'),
('Suitcase Carry',['stability','core','unilateral','ipsilateral'],'Dumbbells','Carry','Frontal','Intermediate','anti-lateral flexion'),
('Bear Crawl',['coordination','core','bilateral'],'Bodyweight','Locomotion','Multi-planar','Intermediate','whole-body coordination'),
('Half Kneeling Pallof Press',['stability','core','unilateral'],'Cable/Machine','Anti-rotation','Transverse','Intermediate','anti-rotation control'),
('T-Spine Windmill',['corrective','mobility','unilateral'],'Bodyweight','Rotation','Transverse','Beginner','thoracic rotation'),
('90/90 Hip Flow',['corrective','mobility'],'Bodyweight','Hip Rotation','Transverse','Beginner','hip mobility'),
('Ankle Dorsiflexion Rocker',['corrective','mobility'],'Bodyweight','Ankle Mobility','Sagittal','Beginner','ankle mobility'),
('Band Face Pull',['corrective','upper','activation'],'Resistance Bands','Scapular Retraction','Transverse','Beginner','scapular control'),
('Medicine Ball Scoop Toss',['power','rotation','sport','unilateral'],'Medicine Ball','Throw','Transverse','Advanced','rotational power'),
('Medicine Ball Chest Pass',['power','upper','bilateral'],'Medicine Ball','Throw','Sagittal','Intermediate','upper-body power'),
('Push Press',['power','upper','bilateral'],'Barbell','Vertical Push','Sagittal','Advanced','full-body power'),
('Dumbbell Snatch',['power','unilateral'],'Dumbbells','Olympic Pull','Multi-planar','Advanced','explosive unilateral power'),
('Lateral Bound and Stick',['agility','power','unilateral'],'Bodyweight','Jump','Frontal','Advanced','deceleration and lateral power'),
('Reactive Cone Drill',['agility','coordination'],'Cones','Change of Direction','Multi-planar','Advanced','reactive agility'),
('Lateral Shuffle to Sprint',['agility','speed'],'Cones','Acceleration','Frontal','Advanced','lateral-to-linear transition'),
('Acceleration Sprint 10m',['speed','anaerobic'],'Cones','Sprint','Sagittal','Advanced','acceleration'),
('Repeated Sprint 20m',['speed','anaerobic'],'Cones','Sprint','Sagittal','Advanced','repeated sprint ability'),
('Pogo Jumps',['plyometric','power'],'Bodyweight','Jump','Sagittal','Intermediate','elastic reactivity'),
('Split Squat Jump',['plyometric','power','unilateral'],'Bodyweight','Jump','Sagittal','Advanced','single-leg power'),
('Depth Drop to Stick',['plyometric','stability'],'Box/Bench','Landing','Sagittal','Advanced','landing mechanics'),
('Single Arm Row + Opposite Shoulder Press on Balance Pad',['power','coordination','upper','unilateral','contralateral','advanced'],'Dumbbells','Pull + Push','Multi-planar','Elite','high-level integrated coordination'),
('Reaction Ball Catch',['coordination','sport'],'Bodyweight','Reaction','Multi-planar','Advanced','visual-motor reaction'),
('Mirror Footwork',['coordination','agility','sport'],'Bodyweight','Footwork','Multi-planar','Advanced','reactive neuromuscular coordination'),
('Shadow Boxing',['sport','anaerobic','coordination'],'Bodyweight','Striking','Multi-planar','Advanced','combat-specific conditioning'),
('Sprawl to Stand',['sport','anaerobic','coordination'],'Bodyweight','Ground Transition','Multi-planar','Advanced','combat transition'),
('Shadow Kick Combination',['sport','coordination'],'Bodyweight','Striking','Multi-planar','Advanced','karate-specific skill'),
('Kumite Reaction Step',['sport','agility','coordination'],'Cones','Reaction','Multi-planar','Advanced','kumite reaction'),
('Swimming Band Pull Pattern',['sport','upper'],'Resistance Bands','Pull','Sagittal','Intermediate','swim-specific shoulder endurance'),
('Streamline Squat Jump',['sport','power'],'Bodyweight','Jump','Sagittal','Advanced','swimming start/streamline power'),
('Soccer Ball Reactive Touch',['sport','coordination','agility'],'Cones','Ball Skill','Multi-planar','Advanced','sport-specific reaction'),
('Goalkeeper Lateral Dive Pattern',['sport','agility','power'],'Bodyweight','Dive','Frontal','Advanced','goalkeeper lateral power'),
('Winger Curved Sprint',['sport','speed'],'Cones','Sprint','Multi-planar','Advanced','winger acceleration and curved running'),
('Tennis Split Step + Crossover',['sport','agility','coordination'],'Cones','Footwork','Multi-planar','Advanced','tennis movement'),
('Metcon Sled Push',['metcon','anaerobic'],'Sled','Push','Sagittal','Advanced','high-output conditioning'),
('Battle Rope Intervals',['metcon','anaerobic'],'Battle Rope','Wave','Multi-planar','Intermediate','upper-body conditioning'),
('Bike Sprint',['metcon','anaerobic'],'Bike/Row/SkiErg','Cycle','Sagittal','Intermediate','anaerobic conditioning'),
('Row Intervals',['metcon','aerobic'],'Bike/Row/SkiErg','Row','Sagittal','Intermediate','aerobic power'),
('Burpee',['metcon','anaerobic'],'Bodyweight','Burpee','Multi-planar','Intermediate','full-body conditioning'),
('Bodyweight Squat',['strength','lower','bilateral'],'Bodyweight','Squat','Sagittal','Beginner','general lower-body volume'),
]
