# name|tags|equipment|pattern|plane|level|purpose
RAW=[
("Goblet Squat","strength lower squat bilateral","Dumbbells","squat","sagittal","General","knee strength"),
("Barbell Back Squat","strength lower squat bilateral","Barbell","squat","sagittal","Advanced","max lower strength"),
("Front Squat","strength lower squat bilateral","Barbell","squat","sagittal","Advanced","quad/trunk strength"),
("Rear Foot Elevated Split Squat","strength lower unilateral contralateral","Dumbbells","lunge","sagittal","Intermediate","unilateral strength"),
("Reverse Lunge","strength lower unilateral","Dumbbells","lunge","sagittal","General","unilateral strength"),
("Lateral Lunge","strength lower unilateral frontal","Dumbbells","lunge","frontal","General","frontal strength"),
("Single Leg RDL","strength lower unilateral contralateral hinge","Dumbbells","hinge","sagittal","Intermediate","hip stability"),
("Romanian Deadlift","strength lower hinge bilateral","Barbell","hinge","sagittal","Intermediate","posterior chain"),
("Trap Bar Deadlift","strength lower hinge bilateral","Barbell","hinge","sagittal","Advanced","high-force strength"),
("Hip Thrust","strength lower hinge bilateral","Barbell","hinge","sagittal","Intermediate","hip extension"),
("Bench Press","strength upper push bilateral","Barbell","horizontal push","transverse","Intermediate","pressing strength"),
("Dumbbell Bench Press","strength upper push bilateral","Dumbbells","horizontal push","transverse","General","pressing strength"),
("Incline Dumbbell Press","strength upper push bilateral","Dumbbells","incline push","sagittal","General","upper chest"),
("Overhead Press","strength upper push bilateral","Barbell","vertical push","sagittal","Intermediate","shoulder strength"),
("Single Arm Dumbbell Press","strength upper push unilateral contralateral","Dumbbells","vertical push","sagittal","Intermediate","unilateral press"),
("Landmine Press","strength upper push unilateral contralateral","Landmine","diagonal push","transverse","Intermediate","athletic press"),
("Pull Up","strength upper pull bilateral","Pull-up Bar","vertical pull","sagittal","Intermediate","pulling strength"),
("Lat Pulldown","strength upper pull bilateral","Cable/Machine","vertical pull","sagittal","General","lat strength"),
("Seated Cable Row","strength upper pull bilateral","Cable/Machine","horizontal pull","transverse","General","upper-back strength"),
("Single Arm Dumbbell Row","strength upper pull unilateral contralateral","Dumbbells","horizontal pull","transverse","General","unilateral pulling"),
("Cable Face Pull","strength upper pull stability corrective","Cable/Machine","horizontal pull","transverse","General","scapular control"),
("Band Face Pull","activation corrective upper pull","Resistance Bands","horizontal pull","transverse","General","scapular prep"),
("Dead Bug","corrective activation core stability","Bodyweight","anti-extension","sagittal","General","trunk control"),
("Side Plank","stability core unilateral","Bodyweight","anti-lateral","frontal","General","lateral stability"),
("Pallof Press","stability core anti-rotation","Cable/Machine","anti-rotation","transverse","General","trunk control"),
("Half Kneeling Pallof Press","corrective stability core anti-rotation","Cable/Machine","anti-rotation","transverse","General","hip/trunk control"),
("90/90 Hip Flow","mobility corrective activation","Bodyweight","mobility","transverse","General","hip mobility"),
("T-Spine Windmill","mobility corrective rotation","Bodyweight","rotation","transverse","General","thoracic mobility"),
("Ankle Dorsiflexion Rocker","mobility corrective","Bodyweight","ankle","sagittal","General","ankle mobility"),
("Glute Bridge","activation corrective lower hinge","Bodyweight","hinge","sagittal","General","hip activation"),
("Lateral Bound and Stick","power plyometric agility unilateral frontal","Bodyweight","bound","frontal","Intermediate","lateral power"),
("Skater Bound","power plyometric agility unilateral","Bodyweight","bound","frontal","Intermediate","lateral power"),
("Box Jump","power plyometric bilateral","Box/Bench","jump","sagittal","General","vertical power"),
("Countermovement Jump","power plyometric bilateral","Bodyweight","jump","sagittal","General","jump power"),
("Broad Jump","power plyometric bilateral","Bodyweight","jump","sagittal","General","horizontal power"),
("Split Squat Jump","power plyometric unilateral","Bodyweight","jump","sagittal","Intermediate","unilateral power"),
("Depth Drop to Stick","power plyometric stability","Box/Bench","landing","sagittal","Advanced","landing control"),
("Pogo Jump","power plyometric lower","Bodyweight","jump","sagittal","General","ankle stiffness"),
("Reactive Cone Drill","agility speed coordination sport","Cones","change of direction","frontal","General","reactive agility"),
("Lateral Shuffle to Sprint","agility speed sport","Cones","change of direction","frontal","General","lateral acceleration"),
("Split Stance Punch with Lateral Exit","agility speed coordination sport","Bodyweight","change of direction","frontal","Intermediate","reactive movement"),
("Mirror Footwork","agility coordination sport","Cones","change of direction","frontal","General","reactive footwork"),
("Reaction Ball Catch","coordination neuromuscular sport","Bodyweight","reaction","multi","General","reaction"),
("Single Arm Row + Opposite Shoulder Press on Balance Pad","strength coordination neuromuscular unilateral contralateral upper stability","Dumbbells","combined","multi","Elite","integrated strength"),
("Single Leg RDL + Contralateral Row","strength coordination neuromuscular unilateral contralateral","Dumbbells","combined","multi","Advanced","integrated control"),
("Lateral Lunge + Landmine Press","strength power coordination unilateral contralateral","Landmine","combined","multi","Advanced","integrated strength"),
("Dumbbell Clean to Push Press","power strength upper lower bilateral","Dumbbells","combined","multi","Intermediate","full-body power"),
("Medicine Ball Rotational Scoop Toss","power sport rotation unilateral","Medicine Ball","rotation","transverse","General","rotational power"),
("Medicine Ball Chest Pass","power upper sport","Medicine Ball","horizontal push","transverse","General","upper power"),
("Medicine Ball Overhead Throw","power upper sport","Medicine Ball","overhead","sagittal","General","whole-body power"),
("Medicine Ball Forehand Throw","power sport rotation unilateral","Medicine Ball","rotation","transverse","General","forehand power"),
("Medicine Ball Backhand Throw","power sport rotation unilateral","Medicine Ball","rotation","transverse","General","backhand power"),
("Swimming Band Pull Pattern","sport upper pull activation","Resistance Bands","pull","sagittal","General","swimming shoulder prep"),
("Streamline Squat Jump","sport power plyometric coordination","Bodyweight","jump","sagittal","General","swimming land power"),
("Soccer Ball Reactive Touch","sport coordination agility","Bodyweight","reaction","multi","General","soccer skill"),
("Goalkeeper Lateral Dive Pattern","sport agility power coordination","Bodyweight","dive","frontal","Advanced","goalkeeper movement"),
("Winger Curved Sprint","sport speed agility","Cones","sprint","multi","Advanced","winger acceleration"),
("Tennis Split Step + Crossover","sport agility speed unilateral","Bodyweight","change of direction","frontal","General","tennis footwork"),
("Shadow Boxing","sport speed coordination anaerobic","Bodyweight","rotation","multi","General","boxing skill"),
("Sprawl to Stand","sport power coordination anaerobic","Bodyweight","combined","sagittal","Advanced","MMA movement"),
("Kumite Reaction Step","sport speed agility coordination","Bodyweight","change of direction","multi","Advanced","karate reaction"),
("Shadow Kick Combination","sport power coordination agility","Bodyweight","rotation","multi","Advanced","karate skill"),
("Bike Sprint","metcon anaerobic aerobic","Bike/Row/SkiErg","conditioning","sagittal","General","conditioning"),
("Row Intervals","metcon aerobic anaerobic upper lower","Bike/Row/SkiErg","conditioning","sagittal","General","conditioning"),
("SkiErg Intervals","metcon aerobic upper","Bike/Row/SkiErg","conditioning","sagittal","General","conditioning"),
("Battle Rope Intervals","metcon anaerobic upper","Battle Rope","conditioning","sagittal","General","conditioning"),
("Sled Push","metcon anaerobic lower strength","Sled","push","sagittal","Intermediate","loaded acceleration"),
("Burpee","metcon anaerobic","Bodyweight","combined","sagittal","General","conditioning"),
("Shuttle Sprint","metcon anaerobic speed","Cones","sprint","multi","General","COD conditioning")]
EX=[(n,set(t.split()),e,p,pl,l,pur) for n,t,e,p,pl,l,pur in RAW]
META={x[0]:{"cats":x[1],"equipment":x[2],"pattern":x[3],"plane":x[4],"level":x[5],"purpose":x[6]} for x in EX}
